--para DIMTIEMPO
SELECT 
    DISTINCT FECHA_RECEPCION,
    TO_CHAR(FECHA_RECEPCION, 'YYYY') AS año,
    TO_CHAR(FECHA_RECEPCION, 'MM') AS mes,
    TO_CHAR(FECHA_RECEPCION, 'DD') AS dia,
    TO_CHAR(FECHA_RECEPCION, 'Q') AS trimestre
FROM ORDENES_SERVICIO;

--para SUBDIMGENERO
SELECT DISTINCT GENERO FROM CLIENTES;

-- para SUBDIMTIPOCLIENTE
SELECT DISTINCT TIPO_CLIENTE FROM CLIENTES;

--para DIMCLIENTES
SELECT ID_Cliente, NOMBRE, TIPO_CLIENTE , GENERO,ESTATUS FROM CLIENTES;

--para SUBDIMMARCA
SELECT DISTINCT MARCA FROM VEHICULOS;

--para DIMVEHICULOS
SELECT ID_VEHICULO,MARCA,MODELO,ANIO FROM VEHICULOS;

--para SUBDIMPUESTO
SELECT DISTINCT PUESTO FROM EMPLEADOS;

--para SUBDIMESPECIALIZACION
SELECT DISTINCT ESPECIALIZACION FROM EMPLEADOS;

--para DIMEMPLEADOS
SELECT ID_EMPLEADO, NOMBRE, PUESTO, TURNO, ESPECIALIZACION FROM EMPLEADOS;

--para DIMSERVICIOS
SELECT * FROM SERVICIOS;

--para HECHOSORDENESSERVICIO
 
SELECT o.ID_ORDEN, o.FECHA_RECEPCION, o.ID_CLIENTE, o.ID_VEHICULO, o.ID_EMPLEADO, SUM(d.CANTIDAD) AS CANTIDAD_SERVICIOS, SUM(d.CANTIDAD * s.COSTO) AS COSTO_TOTAL
FROM ORDENES_SERVICIO o
LEFT JOIN DETALLE_SERVICIO d ON o.ID_ORDEN = d.ID_ORDEN 
LEFT JOIN SERVICIOS s ON d.ID_SERVICIO = s.ID_SERVICIO
GROUP BY o.ID_ORDEN, o.FECHA_RECEPCION, o.ID_CLIENTE, o.ID_VEHICULO, o.ID_EMPLEADO;



--para HECHOSDETALLESERVICIOS

SELECT * FROM DETALLE_SERVICIO;
