---Contar
SELECT COUNT(*) FROM CLIENTES;
SELECT COUNT(*) FROM CONTACTOS;
SELECT COUNT(*) FROM CLIENTE_CONTACTO;
SELECT COUNT(*) FROM EMPLEADOS;
SELECT COUNT(*) FROM EMPLEADO_CONTACTO;
SELECT COUNT(*) FROM VEHICULOS;
SELECT COUNT(*) FROM SERVICIOS;
SELECT COUNT(*) FROM ORDENES_SERVICIO;
SELECT COUNT(*) FROM DETALLE_SERVICIO;
SELECT COUNT(*) FROM FACTURAS;


--Emparejando para comparar
SELECT ID_CLIENTE FROM CLIENTES ORDER BY ID_CLIENTE;
SELECT ID_CONTACTO FROM CONTACTOS ORDER BY ID_CONTACTO;
SELECT ID_CLIENTE FROM CLIENTE_CONTACTO ORDER BY ID_CLIENTE;
SELECT ID_EMPLEADO FROM EMPLEADOS ORDER BY ID_CLIENTE;
SELECT ID_EMPLEADO FROM EMPLEADO_CONTACTO ORDER BY ID_EMPLEADO;
SELECT ID_VEHICULO FROM VEHICULOS ORDER BY ID_VEHICULO;
SELECT ID_SERVICIO FROM SERVICIOS ORDER BY ID_SERVICIO;
SELECT ID_ORDEN FROM ORDENES_SERVICIO ORDER BY ID_ORDEN;
SELECT ID_DETALLE FROM DETALLE_SERVICIO ORDER BY ID_DETALLE;
SELECT ID_FACTURA FROM FACTURAS ORDER BY ID_FACTURA;



----Limpieza de Tablas

DELETE FROM CLIENTES;
DELETE FROM CLIENTE_CONTACTO;
DELETE FROM EMPLEADOS;
DELETE FROM CONTACTOS;
DELETE FROM EMPLEADO_CONTACTO;
DELETE FROM DETALLE_SERVICIO;
DELETE FROM FACTURAS;
DELETE FROM SERVICIOS;
DELETE FROM VEHICULOS;
DELETE FROM ORDENES_SERVICIO;
