CREATE USER C##_BD_TALLER_MECANICA IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY PROCEDURE,
ALTER ANY PROCEDURE, ALTER ANY TABLE, DROP ANY TABLE,
DROP ANY PROCEDURE, CREATE ANY SEQUENCE, ALTER ANY SEQUENCE TO C##_BD_TALLER_MECANICA;